<a href="https://colab.research.google.com/github/harshjoshei/051_HarshJoshi/blob/main/Lab_11/PCA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn import datasets
breast_cancer = datasets.load_breast_cancer()
breast_data = breast_cancer.data
breast_labels = breast_cancer.target

print(breast_data.shape)
print(breast_labels.shape)

import numpy as np
labels = np.reshape(breast_labels,(569,1))
final_breast_data = np.concatenate([breast_data,labels],axis=1)
final_breast_data.shape

import pandas as pd
breast_dataset = pd.DataFrame(final_breast_data)
features = breast_cancer.feature_names
features

final_breast_data[0:5]

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(breast_data,
        breast_labels, random_state=26)

print(X_train.shape, X_test.shape)

"""Preprocessing: Principal Component Analysis
-------------------------------------------

We can use PCA to reduce these features to a manageable size, while maintaining most of the information
in the dataset.


"""

from sklearn import decomposition
pca = decomposition.PCA(n_components=20, whiten=True)
pca.fit(X_train)

"""The principal components measure deviations about this mean along
orthogonal axes.


"""

print(pca.components_.shape)

"""With this projection computed, we can now project our original training
and test data onto the PCA basis:


"""

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)
print(X_train_pca.shape)

print(X_test_pca.shape)

"""
Doing the Learning: Support Vector Machines
-------------------------------------------

Now we'll perform support-vector-machine classification on this reduced
dataset:

"""

from sklearn import svm
clf = svm.SVC(C=5., gamma=0.001)
clf.fit(X_train_pca, y_train)

from sklearn import metrics
y_pred = clf.predict(X_test_pca)
print(metrics.classification_report(y_test, y_pred))

"""Another interesting metric is the *confusion matrix*, which indicates
how often any two items are mixed-up. The confusion matrix of a perfect
classifier would only have nonzero entries on the diagonal, with zeros
on the off-diagonal:


"""

print(metrics.confusion_matrix(y_test, y_pred))

"""With Iris Dataset"""

iris = datasets.load_iris()
iris_data = iris.data
iris_labels = iris.target

print(iris_data.shape)
print(iris_labels.shape)

features = iris.feature_names
features

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(iris_data,
        iris_labels, random_state=26)

print(X_train.shape, X_test.shape)

"""Preprocessing: Principal Component Analysis

We can use PCA to reduce these features to a manageable size, while maintaining most of the information in the dataset.
"""

from sklearn import decomposition
pca = decomposition.PCA(n_components=2, whiten=True)
pca.fit(X_train)

print(pca.components_.shape)

X_train_pca = pca.transform(X_train)
X_test_pca = pca.transform(X_test)
print(X_train_pca.shape)

print(X_test_pca.shape)

from sklearn import svm
clf = svm.SVC(C=5., gamma=0.001)
clf.fit(X_train_pca, y_train)

from sklearn import metrics
y_pred = clf.predict(X_test_pca)
print(metrics.classification_report(y_test, y_pred))

print(metrics.confusion_matrix(y_test, y_pred))

(569, 30)
(569,)
(426, 30) (143, 30)
(20, 30)
(426, 20)
(143, 20)
              precision    recall  f1-score   support

           0       0.93      0.85      0.89        47
           1       0.93      0.97      0.95        96

    accuracy                           0.93       143
   macro avg       0.93      0.91      0.92       143
weighted avg       0.93      0.93      0.93       143

[[40  7]
 [ 3 93]]
(150, 4)
(150,)
(112, 4) (38, 4)
(2, 4)
(112, 2)
(38, 2)
              precision    recall  f1-score   support

           0       1.00      1.00      1.00        13
           1       0.55      1.00      0.71        12
           2       1.00      0.23      0.38        13

    accuracy                           0.74        38
   macro avg       0.85      0.74      0.69        38
weighted avg       0.86      0.74      0.69        38

[[13  0  0]
 [ 0 12  0]
 [ 0 10  3]]
